### PR TITLE
Removed auto enroll checkbox from CCX coash dashboard

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
In this PR I removed auto enrollment checkbox from CCX coash dashboard and Inside controller 
view.py/ccx_invite(request, course) I made auto_enroll true
ccx_coash_dashboard
#21

### CODE REVIEW

**Comment by pdpinch** [comment]
@bdero

**Comment by pdpinch** [comment]
@amir-qayyum-arbisoft The branch you are PR'ing against (feature-pocs) has been rebased, so you'll need to rebase as well. 

Right now the diff on this PR is way too big.

**Comment by amir-qayyum-arbisoft** [comment]
ok sure

**Comment by amir-qayyum-arbisoft** [comment]
@pdpinch  Done with merge base

**Comment by bdero** [comment]
Should I still review this? If so, this PR this should probably be directed toward `edx/edx-platform` master, right?

**Comment by amir-qayyum-arbisoft** [comment]
@bdero I am going to close this one, you can see this PR on edx/edx-platform https://github.com/edx/edx-platform/pull/7833

**Pull request closed without merging**
